spring.application.name=event-platform

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/event_platform}
spring.datasource.username=${DB_USERNAME:event_platform}
spring.datasource.password=${DB_PASSWORD:event_platform}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
