CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    document VARCHAR(255) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    capacity INTEGER NOT NULL,
    registered_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT chk_events_dates CHECK (end_date > start_date),
    CONSTRAINT chk_events_capacity CHECK (capacity > 0),
    CONSTRAINT chk_events_registered_count CHECK (
        registered_count >= 0 AND registered_count <= capacity
    ),
    CONSTRAINT chk_events_status CHECK (
        status IN ('SCHEDULED', 'ACTIVE', 'FINISHED', 'CANCELLED')
    )
);

CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT fk_registrations_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_registrations_event FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT uk_registrations_user_event UNIQUE (user_id, event_id),
    CONSTRAINT chk_registrations_status CHECK (
        status IN ('CONFIRMED', 'CANCELLED', 'WAITING_LIST')
    )
);

CREATE INDEX idx_registrations_event ON registrations (event_id);
CREATE INDEX idx_registrations_user ON registrations (user_id);
CREATE INDEX idx_registrations_waiting_list
    ON registrations (event_id, registration_date)
    WHERE status = 'WAITING_LIST';
